# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f54b0a76aef55360caadb5ccd5959fc0de0dfe0cd40b875e52f7f26b18495b06243215a79d8d66cf1cd82a9bc62d44dadda99a148af21d24b59bd00da4535039

test:
  secret_key_base: 2eb336bbd4582fb4ec1cf2f8c08264a33134584cd4a85ac3a07ace1b83d035b520e83f73ed6e4a46db28281469bfa860f7a035202ae7f26337aace611f70cd35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
